on:
    schedule:
        - cron: "*/5 * * * *"
jobs:
    hello_world:
        runs-on: ubuntu-latest
        steps:
            - name: Prints hello world
              run: echo "Hello World"
            - name: Next thing
              run: echo "Foo Bar"