on:
    # schedule:
    #     - cron: "*/5 * * * *"
    workflow_dispatch:
env:
    GH_TOKEN: ${{ github.token }}
jobs:
    hello_world:
        runs-on: ubuntu-latest
        steps:
            - name: Prints hello world
              run: echo "Hello World"
            - name: Next thing
              run: echo "Foo Bar"
    gh-repo-sync:
        runs-on: ubuntu-latest
        steps:
            - name: Sync drewbrokke/liferay-portal to liferay/liferay-portal
              run: gh repo sync --source liferay/liferay-portal liferay-devtools/liferay-portal